---
# This playbook configure an atomic cluster.

- name: apply common configuration to all nodes
  hosts: atomic_all
  remote_user: root

  roles:
    - common

- name: configure the kubernetes master
  hosts: atomic-master
  remote_user: root

  roles:
    - master

- name: configure the kubernetes nodes
  hosts: atomic_nodes
  remote_user: root

  roles:
    - node
