---
# See https://support.ansible.com/hc/en-us/articles/201958037-Reboot-a-server-and-wait-for-it-to-come-back

- name: Reboot server
  command: systemctl reboot
  async: 0
  poll: 0
  ignore_errors: true

- name: Wait for server to restart
  local_action:
    module: wait_for
      host={{ ansible_hostname }}
      port=22
      delay=1
      timeout=120
    sudo: false