---

- name: Created local registry
  file:
    path: /var/roothome/.local-registry.created
    state: touch

- name: Changed local registry context
  file:
    path: /var/roothome/.local-registry-context.changed
    state: touch

- name: Reload systemctl
  command: /usr/bin/systemctl daemon-reload

- name: Enable local-registry service
  service:
    name: local-registry
    enabled: yes
    state: restarted
