---

- name: Create local registry
  command: >
    docker create -p 5000:5000 \
    -v /var/lib/local-registry:/srv/registry \
    -e STANDALONE=false \
    -e MIRROR_SOURCE=https://registry-1.docker.io \
    -e MIRROR_SOURCE_INDEX=https://index.docker.io \
    -e STORAGE_PATH=/srv/registry \
    --name=local-registry registry
  args:
    creates: /var/roothome/.local-registry.created
  notify:
    - Created local registry

- name: Init SELinux context on local registry
  file:
    path: "/var/lib/local-registry"
    setype: "svirt_sandbox_file_t"
    recurse: yes
    state: directory
  notify: Changed local registry context
